### ISSUE TITLE
rotate, scale, and nonuniform_scale methods for Mat4

### ISSUE THREAD

**Issue by jakbyte** [termhn/ultraviolet#27]
As `Mat4` (and `Wat4`) already have `translate` and `translated` methods, it would make sense for it to also have `rotate`, `rotated`, `scale`, `scaled`, `nonuniform_scale`, and `nonuniform_scaled` methods.

**Comment by jakbyte** [comment]
Never mind. I just found `Isometry3` and `Similarity3`. Sorry.

**Comment by termhn** [comment]
I've been debating this because, on the one hand, Mat4s are generally used as homogeneous 3d matrices, and you could add these methods with that assumption. On the other, these ops also all have parallels in 4d, and are inherently 3d operations. So they currently exist on Mat3 and you can then do `into_homogeneous()` to turn it into a homogeneous Mat4. Should be just as fast after the optimizer.
