### ISSUE TITLE
[Question] SIMD on if-cases

### ISSUE THREAD

**Issue by Turakar** [termhn/ultraviolet#90]
Thanks for the cool library! I want to use SIMD instructions for the following code, but I was not able to understand the methods working on the signs of individual components due to the lack of documentation. Could you tell me, if this is possible with the current `ultraviolet`?
```rust
// all variables are of type f32, but should be of type f32x8
let beta = if x >= 0.0 {
    alpha
} else {
    TWO_PI - alpha
};
```
What would also help: What exactly does the `sign_bit()` function do?

**Comment by termhn** [comment]
Yeah so what you'll need to do is create a comparison mask by using one of the comparison functions in `wide` ([`cmp_ge`](https://docs.rs/wide/0.6.2/wide/struct.f32x8.html#impl-CmpGe%3Cf32%3E in this case)) and then [`blend`](https://docs.rs/wide/0.6.2/wide/struct.f32x8.html#method.blend) between the two possible output values based on that mask: 

```rust
let mask = x.cmp_ge(0.0);
let beta = mask.blend(alpha, TWO_PI - alpha);
```

As far as `sign_bit`, that will create a mask based on the sign bit of each lane... this isn't logically equivalent to `cmp_lt(0.0)`, though, because `-0.0` is a thing

**Comment by Turakar** [comment]
Thanks!
